DATABRICKS_INSTANCE: "https://" 
TOKEN: "*****************"
new_runtime_version: "15.4.x-scala2.12" 
cluster_id: "********"
cluster_ids_to_revert: ["cluster_id_1","cluster_id2"]
my_volume_path: "/path/volume"
cluster_ids: ["cluster_id_1","cluster_id2"]
single_user_name: "user@.com" 